# Generated by Django 4.0 on 2021-12-08 17:40

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='coding', max_length=100)),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='photos/publications')),
                ('featDesc', models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True)),
                ('excerpt', models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.', max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
