# Generated by Django 4.0 on 2021-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
