# Generated by Django 4.0 on 2021-12-08 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_article_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
