# Generated by Django 4.0 on 2022-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_article_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='month',
            field=models.CharField(choices=[('1', 'JAN'), ('2', 'FEB'), ('3', 'MAR'), ('4', 'APR'), ('5', 'MAY'), ('6', 'JUN'), ('7', 'JUL'), ('8', 'AUG'), ('9', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], default='DEC', max_length=3),
        ),
    ]
