# Generated by Django 4.0 on 2022-03-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_article_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='month',
            new_name='post_month',
        ),
    ]
