# Generated by Django 4.0 on 2022-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_rename_month_article_post_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_month',
        ),
        migrations.AddField(
            model_name='article',
            name='month',
            field=models.CharField(choices=[('JAN', '1'), ('FEB', '2'), ('MAR', '3'), ('APR', '4'), ('MAY', '5'), ('JUN', '6'), ('JUL', '7'), ('AUG', '8'), ('SEP', '9'), ('OCT', '10'), ('NOV', '11'), ('DEC', '12')], default='DEC', max_length=3),
        ),
    ]
