# Generated by Django 4.0 on 2022-03-03 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_article_post_month_article_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='imgDesc',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='innerImage',
            field=models.ImageField(blank=True, null=True, upload_to='photos/publications'),
        ),
    ]
